### ISSUE TITLE
How to get started with KEDA for durable functions?

### ISSUE THREAD

**Issue by rohannevrikar** [kedacore/keda-scaler-durable-functions#16]
I want to use KEDA for durable functions, but in the [doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda) only a few triggers are supported yet in KEDA, and not Durable functions triggers like ActivityTrigger or OrchestratorTrigger etc. I came across this repo, and tried to follow [Getting Started](https://github.com/kedacore/keda-scaler-durable-functions/blob/master/docs/getting-started.md) doc, but it shows "Please make sure you have the correct access rights and the repository exists" error while trying to clone KEDA and durable scaler repos. Is this project still under development, or is it supposed to be an internal/private project? If yes, is there any other way to use Durable Functions in Kubernetes?

**Comment by tomkerkhove** [comment]
Adding @TsuyoshiUshio @jeffhollan

**Comment by rohannevrikar** [comment]
Never mind, I cloned the repo using https instead of ssh as mentioned in the doc (should have tried this earlier). Thanks for replying, excited to try this out. Closing this issue for now.
